### PR TITLE
Ballistixx99 chest item test

### PR DESCRIPTION
**Pull request by Ballistixx99**

### CODE REVIEW

**Comment by junglechief87** [comment]
What was the issue you were having with entering ruins out of logic? Also on the chest patcher have you confirmed you're not getting double items? And how does this work with things like itemized NPCs? The way it currently works it is stepping around the games native cheat function. If you write items into the chests it should give you double items.

**Comment by Ballistixx99** [comment]
don't worry about this yet, it ended up here on accident , still new to git hub and how everything works here. this is still a work in progress. Basically i made a function in the chest patcher that could place an item into a chest, and since there was already statements to differentiate between it being placed in an event and a chest, just modified the structure of the script output on the chest variant to remove the give item and message parts, so it only gave the item once. As for the script based items, i just changed the names and icons of some null items in the item table for them, one for castaways, one for party members, one for progressive shop rank, and one for skills. For the script based ones removing item give scripts wasn't necessary because the null items won't appear in your inventory anyway

**Comment by Ballistixx99** [comment]
the biggest issue i was having was not being able to test it, couldn't get pyinstaller to build the executable right

**Comment by junglechief87** [comment]
What issue was pyinstaller giving you?

**Comment by Ballistixx99** [comment]
tried to run it on the main file but ran into trouble because the name had a space, so I figure you used a different file to build it, but couldn't figure out which one, they would all either bring up an error or the executable wouldn't work. it fine though, i was able to get it working in an editor at least so I can test it

**Comment by junglechief87** [comment]
well if you try again there are some lines in the shared functions and the gui that you'll see commented out and the comment next to the lines should indicate that one is for building the single file executable. Due to how pyinstaller likes certain things structured I duplicated some file path lines and changed how it followed the file path for when I build the executable and I just leave that line commented out for when I'm not building the executable then uncomment it and comment the line above it out when I want to build.

**Pull request closed without merging**
